-- CREATE INDEX
CREATE INDEX col1Idx ON test2(col1);

-- SHOW INDEX
SHOW INDEX FROM test2;

-- CREATE UNIQUE INDEX
CREATE UNIQUE INDEX col2Idx ON test2(col2);

-- FULLTEXT INDEX
ALTER TABLE test2
ADD FULLTEXT Col3Idx(col3);

SHOW INDEX FROM test2;

-- INDEX 삭제 (ALTER)
ALTER TABLE test2
DROP INDEX Col3Idx;

SHOW INDEX FROM test2;

-- INDEX 삭제 (DROP INDEX)
DROP INDEX col2Idx ON test2;

SHOW INDEX FROM test2;