-- CREATE TABLE AS SELECT
CREATE TABLE city2 AS SELECT * FROM city;

SELECT * FROM city2;

-- CREATE DATABASE
CREATE DATABASE joo;

USE joo;

-- CREATE TABLE
CREATE TABLE test2(
id INT NOT NULL PRIMARY KEY,
col1 INT NULL,
col2 FLOAT NULL,
col3 VARCHAR(45) NULL
);

SELECT * FROM test2;

-- ALTER TABLE
ALTER TABLE test2
ADD col4 INT NULL;

ALTER TABLE test2
MODIFY col4 VARCHAR(45) NULL;

ALTER TABLE test2
DROP col4;